name: UHCAPI
version: 0.5
author: jnath
main: fr.jnath.UHCAPI.bukkit.plugin.UhcAPI
depend: [WorldEdit, VirthiaUtilsAndAPI]
commands:
  config:
    description: permet de configurer l'UHC
    permission: config.use
  goTo:
    description: permet de changer de monde
    permission: goTo.use
  uhc:
    description: uhc cmd